# Generated by Django 3.2.6 on 2021-09-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210908_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Course',
            new_name='course',
        ),
    ]
