# Generated by Django 3.2.6 on 2021-09-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210912_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name_plural': 'wallet'},
        ),
    ]
