# Generated by Django 3.2.6 on 2021-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_ref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
