# Generated by Django 3.2.6 on 2021-09-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecontent_lesson_textcontent_videocontent'),
        ('wallet', '0006_alter_payment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_to_enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payment', to='course.course'),
        ),
    ]
