# Generated by Django 3.2.6 on 2021-09-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('wallet', '0009_payment_transaction_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='account_number',
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_type', models.CharField(blank=True, max_length=500, null=True)),
                ('aaccount_number', models.PositiveIntegerField()),
                ('bank_code', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('recipient_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_account_resolved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_transfers', to='instructor.instructor')),
            ],
        ),
    ]
