# Generated by Django 3.2.6 on 2021-09-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20210915_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='bank_type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
