# Generated by Django 3.2.6 on 2021-09-17 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_transfers_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 3, 34, 817869, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transfers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_log', to='wallet.transfers'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 19, 3, 34, 817869, tzinfo=utc)),
        ),
    ]
