# Generated by Django 3.2.6 on 2021-09-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20210917_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='transfers',
            new_name='transfer',
        ),
    ]
